name: ReleaseCI
on:
  push:
    branches: ['main']
    # paths: ['packages/test1/**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/mainshuttle.sh ${{secrets.AWS_Bucket_Name}} "folder1/myapp1.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp1.zip"

